In [1]:
import numpy  as np


In [2]:
a = np.ones((3,4,2))   # 3d,1d,2d : k,i,j

sum = 0
for i in range(3):
    for j in range(4):
        for k in range(2):
            sum += 1
            a[i,j,k]= sum 

a

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.],
        [13., 14.],
        [15., 16.]],

       [[17., 18.],
        [19., 20.],
        [21., 22.],
        [23., 24.]]])

## MATRICIZATION OF A TENSOR(3d)

In [3]:
# modo 1

ti = list(a.shape)[0]
tj = list(a.shape)[1]
tk = list(a.shape)[2]

b = np.ones((ti*tk,tj))

for i in range(ti):
    for j in range(tj):
        for k in range(tk):
            b[tk*i+k,j] = a[i,j,k]

In [4]:
b

array([[ 1.,  3.,  5.,  7.],
       [ 2.,  4.,  6.,  8.],
       [ 9., 11., 13., 15.],
       [10., 12., 14., 16.],
       [17., 19., 21., 23.],
       [18., 20., 22., 24.]])

## VECTORICIZATION OF A MATRIZ

In [5]:
b.shape

(6, 4)

In [6]:
mi = list(b.shape)[0]
mj = list(b.shape)[1]

c = np.ones((mi*mj))

In [7]:
for i in range(mi):
    for j in range(mj):
        print(mj*i+j)
        c[mj*i+j] = b[i,j]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [8]:
c

array([ 1.,  3.,  5.,  7.,  2.,  4.,  6.,  8.,  9., 11., 13., 15., 10.,
       12., 14., 16., 17., 19., 21., 23., 18., 20., 22., 24.])